src/GotTable.Web/Controllers/AdminEditController.cs
using GotTable.DAO.Administrators;
using GotTable.Library.Administrators;
using GotTable.Library.OperationExceptionLogs;
using GotTable.Web.Filters;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;


namespace GotTable.Web.Controllers
{
    /// <summary>
    /// AdminEdit
    /// </summary>
    [Permission(allowedRoles)]
    public sealed class AdminEditController : UserBaseController
    {
        /// <summary>
        /// AllowedRoles
        /// </summary>
        private const string allowedRoles = "SuperAdmin";

        /// <summary>
        /// IAdministrator
        /// </summary>
        private readonly IAdministrator<AdminDAO> administrator;

        /// <summary>
        /// IAdministratorList
        /// </summary>
        private readonly IAdministratorList<AdminInfoDAO, ListCriteria> administratorList;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="administrator"></param>
        /// <param name="administratorList"></param>
        /// <param name="operationExceptionLog"></param>
        /// <param name="httpContextAccessor"></param>
        public AdminEditController(IAdministrator<AdminDAO> administrator, IAdministratorList<AdminInfoDAO, ListCriteria> administratorList, IOperationExceptionLog operationExceptionLog, IHttpContextAccessor httpContextAccessor) : base(operationExceptionLog, httpContextAccessor)
        {
            this.administrator = administrator;
            this.administratorList = administratorList;
        }

        /// <summary>
        /// Index
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<ViewResult> Index(decimal userId)
        {
            AdminDAO adminDao;
            if (userId == 0)
            {
                adminDao = await administrator.Create();
            }
            else
            {
                adminDao = await administrator.Get(userId);
            }
            ViewBag.TypeList = Common.List.UserTypeList.Get();
            return View(adminDao);
        }

        /// <summary>
        /// Index
        /// </summary>
        /// <param name="admin"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Index(AdminDAO admin)
        {
            if (admin.UserId == 0)
            {
                await administrator.New(admin);
                if (!admin.Status)
                {
                    ViewBag.TypeList = Common.List.UserTypeList.Get();
                    return View(admin);
                }
            }
            else
            {
                await administrator.Save(admin);
            }
            return RedirectToAction("Index", "AdminList", new { @addedBy = identityUser.UserId });
        }

        /// <summary>
        /// ToggleUser
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> ToggleUser(decimal userId)
        {
            var admin = await administrator.Get(userId);
            admin.IsActive = !admin.IsActive;
            await administrator.Save(admin);
            return RedirectToAction("Index", "AdminList", new { addedBy = identityUser.UserId });
        }
    }
}

src/GotTable.Web/Controllers/AdminListController.cs
using GotTable.Common.Enumerations;
using GotTable.DAO.Administrators;
using GotTable.Library.Administrators;
using GotTable.Library.OperationExceptionLogs;
using GotTable.Web.Filters;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;


namespace GotTable.Web.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [Permission(allowedRoles)]
    public sealed class AdminListController : UserBaseController
    {
        /// <summary>
        /// 
        /// </summary>
        private const string allowedRoles = "SuperAdmin";

        /// <summary>
        /// 
        /// </summary>
        private readonly IAdministratorList<AdminInfoDAO, ListCriteria> administratorList;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="administratorList"></param>
        /// <param name="operationExceptionLog"></param>
        /// <param name="httpContextAccessor"></param>
        public AdminListController(IAdministratorList<AdminInfoDAO, ListCriteria> administratorList, IOperationExceptionLog operationExceptionLog, IHttpContextAccessor httpContextAccessor) : base(operationExceptionLog, httpContextAccessor)
        {
            this.administratorList = administratorList;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="adminType"></param>
        /// <param name="emailAddress"></param>
        /// <param name="adminName"></param>
        /// <param name="status"></param>
        /// <param name="currentPage"></param>
        /// <param name="pageSize"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Index(Enumeration.AdminType? adminType = null, string emailAddress = null, string adminName = "", bool? status = null, int currentPage = 0, int pageSize = 10)
        {
            ViewBag.AdminName = adminName;
            ViewBag.EmailAddress = emailAddress;
            ViewBag.Status = status;
            ViewBag.AdminType = adminType.ToString();
            var criteria = new ListCriteria(adminName, emailAddress, adminType, default, currentPage, pageSize);
            var adminlist = await administratorList.Get(criteria);
            return View(adminlist);
        }
    }
}

src/GotTable.Web/Views/AdminList/Index.cshtml
@model IEnumerable<GotTable.DAO.Administrators.AdminInfoDAO>
@{
    ViewBag.ActiveMenu = "Adminlist";
    ViewBag.ActiveSubMenu = "";
    ViewBag.TotalAgent = Model.Count();
    ViewBag.SalesAgent = Model.Where(x => x.UserType == "SalesAdmin").Count();
    ViewBag.AccountAgent = Model.Where(x => x.UserType == "AccountAdmin").Count();
    Layout = "~/Views/Shared/IndexViewLayout.cshtml";
}

<script type="text/javascript">
    $(document).ready(function () {

            $("#buttonClick").click(function () {
                var adminName = $('#adminName').val();
                var emailAddress = $('#emailAddress').val();
                var adminType = $('#adminType').val();
                var status = $('#status').val();
                var url = '@Html.Raw(Url.Action("Index", "AdminList", new { adminName = "__adminName__", emailAddress = "__emailAddress__", adminType = "__adminType__", status = "__status__" }))';
                window.location.href = url.replace("__adminName__", adminName).replace("__emailAddress__", emailAddress).replace("__adminType__", adminType).replace("__status__", status).replace("#", "%23");
            });

            $('#clearClick').click(function () {
                $('#adminName').val('');
                $('#emailAddress').val('');
                $('#adminType').val('');
                $('#status').val('');
                var adminName = $('#adminName').val();
                var emailAddress = $('#emailAddress').val();
                var adminType = $('#adminType').val();
                var status = $('#status').val();
                var url = '@Html.Raw(Url.Action("Index", "AdminList", new { adminName = "__adminName__", emailAddress = "__emailAddress__", adminType = "__adminType__", status = "__status__" }))';
                window.location.href = url.replace("__adminName__", adminName).replace("__emailAddress__", emailAddress).replace("__adminType__", adminType).replace("__status__", status).replace("#", "%23");
            });
    });
</script>

<div class="main-content">
    <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li><i class="icon-home home-icon"></i><a href="#">Home</a> </li>
            <li><i class="icon-settings"></i>Agent list</li>
        </ul>
    </div>
    <div class="page-content">
        <div class="addheader">
            <span style="float:left"><h2>Agent's List</h2></span>
            <span style="float:right">@Html.ActionLink("New", "Index", "AdminEdit", new { @userId = 0 }, null)</span>
        </div>
        <div class="row" style="height: 40px;">
            <div class="col-xs-9 dine-list">
                <table class="table table-bordered">
                    <tr>
                        <th>
                            Total
                            &nbsp;
                            <span class="bolder" style="color:maroon">@ViewBag.TotalAgent</span>
                        </th>
                        <th>
                            Sales admin
                            &nbsp;
                            <span class="bolder" style="color:maroon">@ViewBag.SalesAgent</span>
                        </th>
                        <th>
                            Account admin
                            &nbsp;
                            <span class="bolder" style="color:maroon">@ViewBag.AccountAgent</span>
                        </th>
                    </tr>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-9">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>
                                User Type
                            </th>
                            <th>
                                First Name
                            </th>
                            <th>
                                Last Name
                            </th>
                            <th>
                                Email Address
                            </th>
                            <th>
                                Status
                            </th>
                            <th>

                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var user in Model)
                        {
                            <tr>
                                <td>
                                    @user.UserType
                                </td>
                                <td>
                                    @user.FirstName
                                </td>
                                <td>
                                    @user.LastName
                                </td>
                                <td>
                                    @user.EmailAddress
                                </td>
                                <td>
                                    <span class='@(user.IsActive == true ? "cusine-yes" : "cusine-no")'>@(user.IsActive == true ? "Active" : "Disable")</span>
                                </td>
                                <td>
                                    <a href="~/AdminEdit/ToggleUser?userId=@user.UserId">@(user.IsActive == true ? "Disable login" : "Enable login")</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="col-xs-3" style="border-left: solid #26d21a 1px; height: 500px;">
                <div class="col-md-12" style="margin-top:3px;">
                    <h3>Filters</h3>
                </div>
                <div class="col-md-12" style="margin-top:10px;">
                    <span class="text-danger bolder">Email address</span>
                    <br />
                    <input type="text" id="emailAddress" class="form-control" value='@ViewBag.EmailAddress' placeholder="Search for email address" />
                </div>
                <div class="col-md-12" style="margin-top:10px;">
                    <span class="text-danger bolder">Name</span>
                    <br />
                    <input type="text" id="adminName" class="form-control" value='@ViewBag.AdminName' placeholder="Search for name" />
                </div>
                <div class="col-md-12" style="margin-top:10px;">
                    <span class="text-danger bolder">Admin type</span>
                    <br />
                    <select class="form-control" id="adminType">
                        <option selected value="">All</option>
                        <option selected="@(ViewBag.AdminType == "SalesAdmin" ? "selected" : "")" value="SalesAdmin">Sales admin</option>
                        <option selected="@(ViewBag.AdminType == "AccountAdmin" ? "selected" : "")" value="AccountAdmin">Account admin</option>
                    </select>
                </div>
                <div class="col-md-12" style="margin-top:10px;">
                    <span class="text-danger bolder">Inactive admin(s)</span>
                    <br />
                    <select class="form-control" id="status">
                        <option value="">All</option>
                        <option value="false" selected="@(ViewBag.Status == false ? "selected" : "")">
                            Yes
                        </option>
                    </select>
                </div>
                <div class="col-md-6" style="margin-top:30px;">
                    <input id="buttonClick" type="button" value="Search" class="btn btn-success" />
                </div>
                <div class="col-md-6" style="margin-top:30px;">
                    <input id="clearClick" type="button" value="Clear" class="btn btn-success" style="background-color:maroon !important;" />
                </div>
            </div>
        </div>
    </div>
</div>