src/GotTable.Web/Controllers/DineInEditController.cs
using GotTable.Common.List;
using GotTable.DAO.Bookings.DineIn;
using GotTable.Library.OperationExceptionLogs;
using GotTable.Library.RestaurantBookings;
using GotTable.Web.Filters;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;


namespace GotTable.Web.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [Permission(allowedRoles)]
    public sealed class DineInEditController : UserBaseController
    {
        /// <summary>
        /// 
        /// </summary>
        private const string allowedRoles = "HotelAdmin";

        /// <summary>
        /// 
        /// </summary>
        private readonly IDineIn dineIn;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="operationExceptionLog"></param>
        /// <param name="dineIn"></param>
        /// <param name="httpContextAccessor"></param>
        public DineInEditController(IOperationExceptionLog operationExceptionLog, IDineIn dineIn, IHttpContextAccessor httpContextAccessor) : base(operationExceptionLog, httpContextAccessor)
        {
            this.dineIn = dineIn;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="bookingId"></param>
        /// <param name="isRead"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Index(decimal bookingId, bool isRead)
        {
            if (isRead)
            {
                await dineIn.MarkAsRead(bookingId);
            }
            var dineInModel = await dineIn.Get(bookingId);
            ViewBag.DineInStatusList = DineInStatusList.Get();
            return View(dineInModel);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> NewStatus(DineInStatusDAO model)
        {
            await dineIn.New(model);
            return RedirectToAction("Index", new { bookingId = model.BookingId, isRead = false });
        }
    }
}

src/GotTable.Web/Controllers/TransactionController.cs
using GotTable.Library.OperationExceptionLogs;
using GotTable.Library.RestaurantBookings;
using GotTable.Web.Filters;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;


namespace GotTable.Web.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [Permission(allowedRoles)]
    public sealed class TransactionController : UserBaseController
    {
        /// <summary>
        /// 
        /// </summary>
        private const string allowedRoles = "HotelAdmin";

        /// <summary>
        /// 
        /// </summary>
        private readonly IRestaurantBookingList restaurantBookingList;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="restaurantBookingList"></param>
        /// <param name="operationExceptionLog"></param>
        /// <param name="httpContextAccessor"></param>
        public TransactionController(IRestaurantBookingList restaurantBookingList, IOperationExceptionLog operationExceptionLog, IHttpContextAccessor httpContextAccessor) : base(operationExceptionLog, httpContextAccessor)
        {
            this.restaurantBookingList = restaurantBookingList;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="restaurantId"></param>
        /// <param name="bookingDate"></param>
        /// <param name="dtStartDate"></param>
        /// <param name="dtEndDate"></param>
        /// <param name="bookingType"></param>
        /// <param name="currentPage"></param>
        /// <param name="pageSize"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Index(decimal restaurantId, DateTime? bookingDate, DateTime? dtStartDate, DateTime? dtEndDate, string bookingType = "", int currentPage = 0, int pageSize = 10)
        {
            if (bookingDate.HasValue)
            {
                var model = await restaurantBookingList.Get(restaurantId, (DateTime)bookingDate, currentPage, pageSize);
                ViewBag.ActiveSubMenu = bookingType;
                return View(model);
            }
            else
            {
                var model = await restaurantBookingList.Get(restaurantId, (DateTime)dtStartDate, (DateTime)dtEndDate, currentPage, pageSize);
                ViewBag.ActiveSubMenu = bookingType;
                return View(model);
            }
        }
    }
}

src/GotTable.Web/Views/Transaction/Index.cshtml
@using GotTable.Common.Enumerations;
@model IEnumerable<GotTable.DAO.Bookings.BookingDAO>
@{
    ViewBag.ActiveMenu = "Bookings";
    ViewBag.New = Model.Where(x => x.IsRead == false).Count();
    ViewBag.Pending = Model.Where(x => x.CurrentStatus == "Confirm").Count();
    ViewBag.Completed = Model.Where(x => x.CurrentStatus == "Complete").Count();
    ViewBag.Cancelled = Model.Where(x => x.CurrentStatus != "Complete" && x.CurrentStatus != "Confirm").Count();
    Layout = "~/Views/Shared/IndexViewLayout.cshtml";
}

<div class="main-content">
    <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li><i class="icon-home home-icon"></i><a href="#">Home</a></li>
            <li><i class="icon-desktop desktop-icon"></i>&nbsp;@ViewBag.ActiveSubMenu Booking</li>
        </ul>
    </div>
    <div class="page-content">
        <div class="addheader">
            <span style="float:left"><h2> Transaction's List</h2></span>
            <span style="float:right">&nbsp;</span>
        </div>

        <div class="row" style="height: 40px;">
            <div class="col-xs-12 col-sm-9 dine-list">
                <ul>
                    <li>
                        <button type="button" class="btn btn-primary pcc-btn cancel">
                            Pending
                            <span id="lblCurrentBookingPending" class="badge pcc-badge">@ViewBag.Pending</span>
                        </button>
                    </li>

                    <li>
                        <button type="button" class="btn btn-primary pcc-btn complete">
                            Completed
                            <span id="lblCurrentBookingCompleted" class="badge pcc-badge">@ViewBag.Completed</span>
                        </button>
                    </li>
                    <li>
                        <button type="button" class="btn btn-primary pcc-btn cancel">
                            Cancelled
                            <span id="lblCurrentBookingCancelled" class="badge pcc-badge">@ViewBag.Cancelled</span>
                        </button>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped" id="tblDineInBooking">
                        <thead>
                            <tr>
                                <th>
                                    Booking
                                </th>
                                <th>
                                    Detail
                                </th>
                                <th>
                                    User
                                </th>
                                <th>
                                    Email address
                                </th>
                                <th>
                                    Phone number
                                </th>
                                <th>
                                    Status
                                </th>
                                <th></th>
                            </tr>
                        </thead>

                        @if (Model != null)
                        {
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td style='@(!item.IsRead ? "font-weight:bold;" : "")'>
                                        @item.DateTimeForOrder
                                        @if (!item.IsRead)
                                        {
                                            <br />
                                            <br />
                                            <span style="padding:2px 8px; border-radius:5px; border: dashed #000000 1px;">New</span>
                                        }
                                    </td>
                                    <td style='@(!item.IsRead ? "font-weight:bold;" : "")'>
                                        @if (item.BookingType == Enumeration.BookingType.DineIn.ToString())
                                        {
                                            @item.BookingType
                                            <br />
                                            <br />
                                            @item.TableName
                                        }
                                        else
                                        {
                                            @item.BookingType
                                        }
                                    </td>
                                    <td style='@(!item.IsRead ? "font-weight:bold;" : "")'>
                                        @item.Name
                                    </td>
                                    <td style='@(!item.IsRead ? "font-weight:bold;" : "")'>
                                        @item.EmailAddress
                                    </td>
                                    <td style='@(!item.IsRead ? "font-weight:bold;" : "")'>
                                        @item.PhoneNumber
                                    </td>
                                    <td style='@(!item.IsRead ? "font-weight:bold;" : "")'>
                                        @item.CurrentStatus
                                    </td>
                                    <td>
                                        @if (item.BookingType == Enumeration.BookingType.DineIn.ToString())
                                        {
                                            @Html.ActionLink("Detail", "Index", "DineInEdit", new { bookingId = item.BookingId, isRead = !item.IsRead}, null)
                                        }
                                        else if (item.BookingType == Enumeration.BookingType.Delivery.ToString())
                                        {
                                            @Html.ActionLink("Detail", "Index", "DeliveryEdit", new { bookingId = item.BookingId, isRead = !item.IsRead }, null)
                                        }
                                        else if (item.BookingType == Enumeration.BookingType.Takeaway.ToString())
                                        {
                                            @Html.ActionLink("Detail", "Index", "TakeawayEdit", new { bookingId = item.BookingId, isRead = !item.IsRead }, null)
                                        }
                                    </td>
                                </tr>
                                }
                            </tbody>
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>